apiVersion: apps/v1
kind: Deployment
metadata:
  name: willsapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: willsapp
  template:
    metadata:
      labels:
        app: willsapp
    spec:
      containers:
      - image: docker.io/wil42/playground:v2
        name: willsapp
        ports:
        - containerPort: 8888
